### ISSUE TITLE
bug in SPARQL for 1hop-2i/0qual

### ISSUE THREAD

**Issue by Kelaproth** [DimitrisAlivas/StarQE#1]
It looks like the SPARQL is not executable. should line 37 in test/validation and line 22 in train:
`FILTER ((?s1 != ?o2_s0) || (?s1 = ?o2_s0 && str(?p0)< str(?1) ))`
be
`FILTER ((?s1 != ?o2_s0) || (?s1 = ?o2_s0 && str(?p0)< str(?p1) ))`
?

**Comment by miselico** [comment]
Yes, you are right. 

If you want to generate your own queries, I'd suggest looking into https://github.com/miselico/graph_query_sampler which has better support for query generation with other datasets.

**Comment by miselico** [comment]
Fixed, thanks. Note: i think that this mistake in the formula never affects the generated queries.
